<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_APPLY</name>
   <tag></tag>
   <elementGuidId>68321d45-cf3c-40ed-a21d-72e63b909bd2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.antd5-btn.css-dev-only-do-not-override-1n2pxdy.antd5-btn-primary.antd5-btn-color-primary.antd5-btn-variant-solid.superset-button.superset-button-primary.cta.css-966myn-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type = 'button' and (text() = 'APPLY' or . = 'APPLY')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-test=&quot;date-filter-control__apply-button&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>65f2b89a-e4cb-4680-a062-a4fdee007d21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>date-filter-control__apply-button</value>
      <webElementGuid>15ec8c73-b79a-4abd-8999-092266e9ab77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>74426588-f9ba-4bbc-9825-6d896c5463da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>antd5-btn css-dev-only-do-not-override-1n2pxdy antd5-btn-primary antd5-btn-color-primary antd5-btn-variant-solid superset-button superset-button-primary cta css-966myn-button</value>
      <webElementGuid>6c48a32e-18f2-4d49-bca4-48dbba591ee6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>APPLY</value>
      <webElementGuid>516dc803-50fa-4479-a349-60f9308349e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;antd5-popover css-dev-only-do-not-override-1n2pxdy time-range-popover css-dev-only-do-not-override-1n2pxdy antd5-popover-placement-right&quot;]/div[@class=&quot;antd5-popover-content&quot;]/div[@class=&quot;antd5-popover-inner&quot;]/div[@class=&quot;antd5-popover-inner-content&quot;]/div[@class=&quot;css-qv0ghl&quot;]/div[@class=&quot;footer&quot;]/button[@class=&quot;antd5-btn css-dev-only-do-not-override-1n2pxdy antd5-btn-primary antd5-btn-color-primary antd5-btn-variant-solid superset-button superset-button-primary cta css-966myn-button&quot;]</value>
      <webElementGuid>5359851f-d358-44ad-ab39-9c1a2cc8ce7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Parkengage/iframe</value>
      <webElementGuid>dd31abd2-cf24-4c1a-a39f-b45cad029a60</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[10]</value>
      <webElementGuid>c7b6ad37-3706-428e-9124-8d1adcee2543</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CANCEL'])[1]/following::button[1]</value>
      <webElementGuid>91b8bd9e-0874-46a6-aba0-12b82808405e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Actual time range'])[1]/following::button[2]</value>
      <webElementGuid>91755ad2-9dc2-4952-ad38-da59ad3b14c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/button[2]</value>
      <webElementGuid>38938878-f0b4-402b-826e-13972fded820</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'APPLY' or . = 'APPLY')]</value>
      <webElementGuid>d591b0da-dbd4-43c7-a7c6-4a95d375afc9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
