<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Facility_options</name>
   <tag></tag>
   <elementGuidId>c33342fe-bd21-43fc-b83c-280bcc84eea3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ant-select-selector</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[2]/div/div/div[2]/div[2]/div/div/form/div/div/div[2]/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.ant-select-selector >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>016f0b2f-d45f-40b7-b680-2aa81a91f3d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-select-selector</value>
      <webElementGuid>760fb526-b4bb-426d-b7f6-7da1d5af288d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> 8 options</value>
      <webElementGuid>0f8573c9-e7df-4d6c-af16-2751f2ada3b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;css-1u8ar8f&quot;]/div[@class=&quot;css-1bl3vr5&quot;]/div[@class=&quot;css-1a2qin2&quot;]/div[@class=&quot;open css-1116wq&quot;]/div[@class=&quot;open css-14pwj7q&quot;]/div[@class=&quot;css-lmih2o&quot;]/div[@class=&quot;css-wlt4i6&quot;]/div[1]/form[@class=&quot;ant-form ant-form-vertical css-pph8ry&quot;]/div[1]/div[@class=&quot;ant-row ant-form-item css-1q22i2n&quot;]/div[@class=&quot;ant-col ant-form-item-control&quot;]/div[@class=&quot;ant-form-item-control-input&quot;]/div[@class=&quot;ant-form-item-control-input-content&quot;]/div[1]/div[@class=&quot;css-18ea7y2&quot;]/div[1]/div[@class=&quot;css-2hvcmq&quot;]/div[@class=&quot;ant-row ant-form-item css-1rah2bg&quot;]/div[@class=&quot;ant-col ant-form-item-control&quot;]/div[@class=&quot;ant-form-item-control-input&quot;]/div[@class=&quot;ant-form-item-control-input-content&quot;]/div[@class=&quot;ant-space ant-space-horizontal ant-space-align-center css-9vktjx&quot;]/div[@class=&quot;ant-space-item&quot;]/div[@class=&quot;select-container css-1l6d282&quot;]/div[@class=&quot;ant-select css-c3ae2p ant-select-multiple ant-select-allow-clear ant-select-show-arrow ant-select-open ant-select-show-search&quot;]/div[@class=&quot;ant-select-selector&quot;]</value>
      <webElementGuid>daa1abe3-90c8-43e3-8e39-ec1fe2f6a8a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Parkengage/iframe</value>
      <webElementGuid>921c66a4-66d6-4852-bc5b-d5d022226291</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div/div/div[2]/div[2]/div/div/form/div/div/div[2]/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div</value>
      <webElementGuid>4c5281b8-9292-45ed-9e50-387d77b3ae11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Facility'])[1]/following::div[18]</value>
      <webElementGuid>055941a4-33c7-4875-a029-8d22c23f1059</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filters'])[1]/following::div[25]</value>
      <webElementGuid>a05cf924-a45f-4976-a427-a129041b60b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Beal House Fort Walton Beachfront'])[1]/preceding::div[4]</value>
      <webElementGuid>7ddd943c-074f-4733-b665-bc1577da6a3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DoubleTree Beach Resort by Hilton Hotel Tampa Bay - North Redington Beach'])[1]/preceding::div[5]</value>
      <webElementGuid>8151302d-9749-4466-8a52-402d158ea94e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div</value>
      <webElementGuid>c56043b4-99b9-43ce-a85e-48203ea583de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' 8 options' or . = ' 8 options')]</value>
      <webElementGuid>f499e3e1-60c8-452a-a673-efc4a7336578</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
