<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Transients</name>
   <tag></tag>
   <elementGuidId>f0672764-5cd4-49dd-8b76-87206e2b8a51</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.editable-title > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='TABS-KtmXaPGDshOIKyAs5ZXlK-tab-TAB-j6ntnNH9adnu1czlVQXXY']/div/div/span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Transients&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8abc9e27-5d73-44e6-bda7-55bd178f40f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>editable-title-input</value>
      <webElementGuid>ab61e97e-c8f9-4a37-a266-4b62ef8c2118</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Transients</value>
      <webElementGuid>f161ac3b-0127-4a87-9e13-988008a6219c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TABS-KtmXaPGDshOIKyAs5ZXlK-tab-TAB-j6ntnNH9adnu1czlVQXXY&quot;)/div[@class=&quot;dragdroppable dragdroppable-column css-1c5yb7h&quot;]/div[@class=&quot;dragdroppable-tab css-v80n4q&quot;]/span[@class=&quot;editable-title&quot;]/span[1]</value>
      <webElementGuid>fc46e073-e633-4b78-83fa-40ed28036f0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Parkengage/iframe</value>
      <webElementGuid>91d35569-5e23-4d72-9e6a-ae910ed634ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='TABS-KtmXaPGDshOIKyAs5ZXlK-tab-TAB-j6ntnNH9adnu1czlVQXXY']/div/div/span/span</value>
      <webElementGuid>2ecadfb3-a913-41de-9228-5311cbc47c2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clear all'])[1]/following::span[2]</value>
      <webElementGuid>77f37c5d-aa22-46c1-969e-8bf6580cfa11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apply filters'])[1]/following::span[3]</value>
      <webElementGuid>73d959f7-25d5-4cac-8c11-8e6d1d9ada7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Operational Dashboard'])[1]/preceding::span[1]</value>
      <webElementGuid>550382f6-8a79-46da-8620-ba0862d46835</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Detail Table'])[1]/preceding::span[3]</value>
      <webElementGuid>c2cec935-3254-43c1-a7d0-d8418a737ebc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Transients']/parent::*</value>
      <webElementGuid>92e74dd7-6b6e-4583-9a4e-ab9f33896023</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/span/span</value>
      <webElementGuid>ed5e9ce8-c081-4cdc-8df1-5a0815a18115</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Transients' or . = 'Transients')]</value>
      <webElementGuid>1cd4f9dc-71bb-4ae4-be67-f0e8ac31508d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
