<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Permits</name>
   <tag></tag>
   <elementGuidId>ed604694-a2d9-4965-aed2-7b42b3547b74</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#TABS-KtmXaPGDshOIKyAs5ZXlK-tab-TAB-Ki2XeJ5bLxj56ezg2tQlB > div.dragdroppable.dragdroppable-column.css-1c5yb7h > div.dragdroppable-tab.css-jik4gi > span.editable-title > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='TABS-KtmXaPGDshOIKyAs5ZXlK-tab-TAB-Ki2XeJ5bLxj56ezg2tQlB']/div/div/span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Permits&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>26e9df67-e650-4f2b-aca4-2c3acb1baac1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>editable-title-input</value>
      <webElementGuid>c46b315c-6fbc-4433-90d2-041af4d2345c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Permits</value>
      <webElementGuid>132d7dd3-afbd-4702-97f6-01078f906acd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TABS-KtmXaPGDshOIKyAs5ZXlK-tab-TAB-Ki2XeJ5bLxj56ezg2tQlB&quot;)/div[@class=&quot;dragdroppable dragdroppable-column css-1c5yb7h&quot;]/div[@class=&quot;dragdroppable-tab css-jik4gi&quot;]/span[@class=&quot;editable-title&quot;]/span[1]</value>
      <webElementGuid>c5e93c81-546b-4e02-97af-d8d78d48f1a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Parkengage/iframe</value>
      <webElementGuid>79074dfc-6d78-4870-ae2a-e5d152870b06</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='TABS-KtmXaPGDshOIKyAs5ZXlK-tab-TAB-Ki2XeJ5bLxj56ezg2tQlB']/div/div/span/span</value>
      <webElementGuid>0aef3581-fac1-4e5d-9e3c-cb88cf36d7a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Detail Table'])[1]/following::span[2]</value>
      <webElementGuid>0bc67710-d7fe-4464-a8be-5d714aac73a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Operational Dashboard'])[1]/following::span[4]</value>
      <webElementGuid>9bd3a29c-9bad-49cd-859f-3e298a438314</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Number of Transients'])[1]/preceding::span[3]</value>
      <webElementGuid>c6337e47-4cec-4f68-bbed-d38567a3035e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[1]/preceding::span[12]</value>
      <webElementGuid>ae729952-2fba-4796-97d3-d943b57be70c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Permits']/parent::*</value>
      <webElementGuid>c6a7ab27-a3f4-40bc-8b3e-11777f07c871</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/span/span</value>
      <webElementGuid>b2d8cd04-ce63-4ad5-bdaa-6110bfdcedaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Permits' or . = 'Permits')]</value>
      <webElementGuid>fa67e0ca-8993-4dc7-a6d8-71c72730f7be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
