<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Time_Period_Selection</name>
   <tag></tag>
   <elementGuidId>7896d439-c3ce-445a-9ca2-e5716558a97f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@aria-label='calendar']//*[name()='svg']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.anticon.anticon-calendar.css-1ifup07 > svg</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-test=&quot;time-range-trigger&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>001e1474-049c-49f9-b739-0ac2cc8e1749</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>64 64 896 896</value>
      <webElementGuid>b31b4492-3d85-4649-96e2-7eb80dd14a1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>focusable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b350e00d-192f-4f38-989c-e2bcd46953ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-icon</name>
      <type>Main</type>
      <value>calendar</value>
      <webElementGuid>8e9eeb5f-654a-4e38-8685-e2870b4ce379</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1em</value>
      <webElementGuid>a262891c-0ccf-4e3b-9f1b-a5cbe385419b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>1em</value>
      <webElementGuid>e24e74d6-511d-44df-9b5a-a024575c67fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>currentColor</value>
      <webElementGuid>a578f7d0-527a-4dbe-a2e0-a0facaf3dc5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>bd1d49ef-f16f-411e-a3e9-5d83908c28f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;css-1u8ar8f&quot;]/div[@class=&quot;css-1bl3vr5&quot;]/div[@class=&quot;css-1a2qin2&quot;]/div[@class=&quot;open css-1116wq&quot;]/div[@class=&quot;open css-14pwj7q&quot;]/div[@class=&quot;css-lmih2o&quot;]/div[@class=&quot;css-wlt4i6&quot;]/div[4]/form[@class=&quot;ant-form ant-form-vertical css-pph8ry&quot;]/div[1]/div[@class=&quot;ant-row ant-form-item css-1q22i2n&quot;]/div[@class=&quot;ant-col ant-form-item-control&quot;]/div[@class=&quot;ant-form-item-control-input&quot;]/div[@class=&quot;ant-form-item-control-input-content&quot;]/div[1]/div[@class=&quot;css-18ea7y2&quot;]/div[1]/div[@class=&quot;css-za9c7s&quot;]/div[@class=&quot;css-1eabcxc&quot;]/div[@class=&quot;antd5-tooltip-open css-1fhy3dq&quot;]/span[@class=&quot;anticon anticon-calendar css-1ifup07&quot;]/svg[1]</value>
      <webElementGuid>9181cb42-917a-4ba3-a075-e4a017b3e54b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Parkengage/iframe</value>
      <webElementGuid>da8ec4d5-3099-4a6a-b1d7-c2619e9cd327</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='previous calendar month'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>ce3a52c9-b112-417c-a69d-5f79c2298bc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Time Period'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>2b1eeacb-ad9f-4670-8d7a-c6be5f3d8f05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filters out of scope (0)'])[1]/preceding::*[name()='svg'][2]</value>
      <webElementGuid>d3df9d9a-076d-400b-9914-73bad69d47ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apply filters'])[1]/preceding::*[name()='svg'][2]</value>
      <webElementGuid>cf4e0c24-554b-4183-839c-0491e2935def</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
